import {
  Bot,
  Building2,
  CircleAlert,
  Headphones,
  KeyRound,
  Landmark,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Workflow,
} from 'lucide-react';
import type { AuditLog, PortalApp } from './types';

export const portalApps: PortalApp[] = [
  {
    code: 'oa',
    name: 'Mirage OA',
    description: '审批、组织、考勤和流程协作的内部办公系统。',
    category: '业务系统',
    entryUrl: '#',
    status: 'online',
    visibility: 'LOGIN',
    tags: ['Spring Boot', 'Workflow', 'RBAC'],
    accent: '#48d7a6',
    icon: Building2,
  },
  {
    code: 'crm',
    name: 'Mirage CRM',
    description: '客户、商机、联系人和销售跟进的客户经营台。',
    category: '业务系统',
    entryUrl: '#',
    status: 'online',
    visibility: 'LOGIN',
    tags: ['React', 'MySQL', 'Pipeline'],
    accent: '#76a7ff',
    icon: Headphones,
  },
  {
    code: 'mall',
    name: 'Mirage Mall',
    description: '商品、订单、会员、营销和交易链路的商城样板。',
    category: '业务系统',
    entryUrl: '#',
    status: 'restricted',
    visibility: 'AUTHORIZED',
    tags: ['Order', 'Payment', 'Inventory'],
    accent: '#f3c05d',
    icon: ShoppingBag,
  },
  {
    code: 'ai-lab',
    name: 'AI Workbench',
    description: '知识库问答、内容生成和 Agent 工具调用实验室。',
    category: 'AI 应用',
    entryUrl: '#',
    status: 'online',
    visibility: 'LOGIN',
    tags: ['LLM', 'RAG', 'Agent'],
    accent: '#e875b7',
    icon: Bot,
  },
  {
    code: 'gateway',
    name: 'API Gateway',
    description: '统一资源服务鉴权、路由、限流和调用观测入口。',
    category: '工具系统',
    entryUrl: '#',
    status: 'draft',
    visibility: 'ADMIN',
    tags: ['Gateway', 'JWT', 'Rate Limit'],
    accent: '#6fd6e8',
    icon: Workflow,
  },
  {
    code: 'finance',
    name: 'Ledger Center',
    description: '面向订单、支付、账务和对账能力的财务中台。',
    category: '实验项目',
    entryUrl: '#',
    status: 'restricted',
    visibility: 'AUTHORIZED',
    tags: ['Ledger', 'Audit', 'Risk'],
    accent: '#d6db70',
    icon: Landmark,
  },
];

export const adminMetrics = [
  { label: '用户总数', value: '248', hint: 'ACTIVE 231 / LOCKED 6', icon: ShieldCheck },
  { label: '今日登录次数', value: '1,406', hint: '成功率 98.1%', icon: KeyRound },
  { label: '接入应用数量', value: '12', hint: '+3 this month', icon: Sparkles },
  { label: '异常登录次数', value: '27', hint: '6 IP locked', icon: CircleAlert },
];

export const auditLogs: AuditLog[] = [
  {
    id: 'AUD-2407',
    actor: 'admin',
    type: 'LOGIN',
    event: 'LOGIN_SUCCESS',
    target: 'Mirage Identity',
    result: 'SUCCESS',
    ip: '127.0.0.1',
    userAgent: 'Chrome 126 / macOS',
    time: '10:28:41',
    failureReason: '',
  },
  {
    id: 'AUD-2406',
    actor: 'system',
    type: 'TOKEN',
    event: 'TOKEN_REFRESH',
    target: 'AI Workbench',
    result: 'SUCCESS',
    ip: '10.24.8.19',
    userAgent: 'Resource Server SDK',
    time: '10:22:03',
    failureReason: '',
  },
  {
    id: 'AUD-2405',
    actor: 'guest',
    type: 'SECURITY',
    event: 'INVALID_REDIRECT_URI',
    target: 'Mirage CRM',
    result: 'FAILED',
    ip: '172.16.1.8',
    userAgent: 'curl/8.4.0',
    time: '10:18:55',
    failureReason: '回调地址不在白名单内',
  },
  {
    id: 'AUD-2404',
    actor: 'admin',
    type: 'ADMIN',
    event: 'CLIENT_SECRET_RESET',
    target: 'Mirage Mall',
    result: 'SUCCESS',
    ip: '127.0.0.1',
    userAgent: 'Chrome 126 / macOS',
    time: '10:04:12',
    failureReason: '',
  },
  {
    id: 'AUD-2403',
    actor: 'operator',
    type: 'ADMIN',
    event: 'USER_CREATED',
    target: 'USER:demo',
    result: 'SUCCESS',
    ip: '127.0.0.1',
    userAgent: 'Chrome 126 / macOS',
    time: '09:58:32',
    failureReason: '',
  },
  {
    id: 'AUD-2402',
    actor: 'guest',
    type: 'LOGIN',
    event: 'LOGIN_FAILED',
    target: 'USER:guest',
    result: 'FAILED',
    ip: '172.16.1.9',
    userAgent: 'Firefox 126 / Windows',
    time: '09:42:19',
    failureReason: '密码错误',
  },
  {
    id: 'AUD-2401',
    actor: 'system',
    type: 'TOKEN',
    event: 'TOKEN_REVOKED',
    target: 'CLIENT:mirage-oa',
    result: 'SUCCESS',
    ip: '10.24.8.22',
    userAgent: 'Authorization Server',
    time: '09:22:05',
    failureReason: '',
  },
];
